lang = {
    'uz': {
        "save_product": "Buyurtmangiz joylandi !",
        "product_price": "Buyurtmangiz uchun qanch tulamoqchisiz !",
        "product_description":"Menga buyurtmangiz haqida malumot bering !",
        "product_title": "Buyurtmangizni nomini kiriting !",
        "fullname": "Ism famileyangizni kiriting !",
        "menu": "Kwork botiga xush kelibsiz !",
        "language": "Bot tilini tanlang",
        "firlanser": "🧑🏻‍💻 Men Firlanserman",
        "customer": "👤 Men buyurtmachiman",
        "change_lang": "🌐 Tilni almashtirish",
        "phone_number": "Telefon raqamni yuboring 👇",
        "vacancies": "💼 Vakasiyalar/Vakansiya joylashtirish",
        "prog_lang": "Qaysi dasturlash tilini bilasiz ?",
        "firlanser_bot": "Vakansiyalarni kurish va buyurtma olish uchun 👇",
        "firlanser_login": "Siz frelansersiz",
        "customer_bot": "Buyurtma berish va buyurtmalarni kurish uchun  👇",
        "order": "🗂 Buyurtma berish",
        "order_history": "Buyurtmalar tarixi",
        "product_id_text":"Buyurtma tartiq raqami : ",
        "product_title_text":"Buyurtma nomi : ",
        "product_description_text":"Buyurtma haqida malumot : ",
        "product_price_text": "narxi : ",
        "product_status_text": "buyurtma holati : ",
        "receive": "Qabul qilish",
        "vacancy_firlanser": "Vakansiyalarni faqat firlanserlar ko'ra oladi.",
        "place_product_id": "Iltimos qabul qilgan buyurtmangizni tartib raqamini kiriting !",
        "product_status_text2": "Qabul qilindi ✅",
        "check_product": "Buyurtma mavjud emas !",
        "customer_product": "Sizda buyurtma mavjud emas !"
    },

    'en': {
        "customer_product":"You do not have an order",
        "check_product": "order is not available",
        "product_status_text2": "Accepted ✅",
        "place_product_id": "Please enter the order number of your received order!",
        "vacancy_firlanser": "Vacancies can only be viewed by freelancers.",
        "receive": "Receive",
        "product_status_text": "case order : ",
        "product_price_text": "price : ",
        "product_description_text": "Order information : ",
        "product_title_text": "Order name : ",
        "product_id_text": "sequence number : ",
        "product_price": "How much would you like to choose for your order?",
        "product_description":"Give me information about your order",
        "product_title": "Enter your product name",
        "prog_lang": "Which programming language do you know ?",
        "fullname": "Enter your fullname",
        "menu": "Welcome to aur Kwork bot !",
        "language": "Choose language of bot",
        "firlanser": "🧑🏻‍💻 I am Freelancer",
        "customer": "👤 I am customer",
        "change_lang": "🌐 Change language",
        "phone_number": "Send phone number 👇",
        "vacancies": "💼 Apply Vacancy/Vacancies",
        "firlanser_bot": "To view vacancies and receive orders 👇",
        "firlanser_login": "You our freelancer",
        "customer_bot": "To place an order and view orders 👇",
        "order": "🗂 To order",
        "order_history": "🗂 History of orders",
        "save_product":"Your order has been placed"
    }
}